### ISSUE TITLE
Cannot resolve symbol

### ISSUE THREAD

**Issue by minimedj** [odoo-ide/pycharm-odoo-old#10]
Please see explanation on the screenshot: https://monosnap.com/file/9F175oLPf0NSqZEaZgqSTNRYjpWdPa

**Comment by ghost** [comment]
What Pycharm Odoo plugin version are you using ? Did you attach https://github.com/trinhanhngoc/odoo-stubs to your project ?

**Comment by minimedj** [comment]
With odoo-stubs it is better. Thanks!
