### ISSUE TITLE
Plugin Error: Plugin "PyCharm Odoo" is incompatible (until build 201.SNAPSHOT < PC-202.6397.98)

### ISSUE THREAD

**Issue by NuevaIT-ext1** [odoo-ide/pycharm-odoo-old#11]
Please enable update to support pycharm version 2020.2. It is very useful pluging. Thanks in Advance.

**Comment by mugagambi** [comment]
Such a useful plugin.
Can't wait for an update to fix it on 2020.2
Thanks for the great work you have been doing!

**Comment by trinhanhngoc** [comment]
Hi. The new version is out with support for 2020.2!. Enjoy the update!

https://github.com/trinhanhngoc/pycharm-odoo/releases/download/v4.2/pycharm-odoo-4.2.zip

**Comment by mugagambi** [comment]
@trinhanhngoc Awesome.
Thanks so much 🎉
