### ISSUE TITLE
Can't resolve some model names

### ISSUE THREAD

**Issue by 6uipoeib** [odoo-ide/pycharm-odoo-old#12]
### Environment:
Odoo 13 with odoo-stub installed
I have tried "Clear Cache and Restart" but still no luck.

### Issue:
Some model names can be resolved but some cannot.

For example, In my project:

`questionnaire_id = fields.Many2one('survey.survey', string='Registration Questionnaire')` 
gives me red lines under 'survey.survey'

however another field
`welcome_email_template = fields.Many2one('mail.template')`
is correct.

both 'survey.survey' and 'mail.template' are odoo models under odoo/odoo/addons. And there are no runtime errors for my environment.

**Comment by ghost** [comment]
Did you include the module `survey` in the manifest ?

**Comment by 6uipoeib** [comment]
Thank you very much. I missed that. After adding dependency it's good now.
