### ISSUE TITLE
Server Action model_id cannot be resolved

### ISSUE THREAD

**Issue by 6uipoeib** [odoo-ide/pycharm-odoo-old#13]
In server action xmls, the `ref` value in `model_id` and `binding_model_id` are all showing "not able to resolve",
For example, In
```
<record id="lunch_order_action_confirm" model="ir.actions.server">
        <field name="name">Lunch: Receive meals</field>
        <field name="model_id" ref="model_lunch_order"/>
        <field name="binding_model_id" ref="model_lunch_order"/>
        <field name="binding_view_types">list</field>
        <field name="state">code</field>
        <field name="code">records.action_confirm()</field>
</record>
```

`ref="model_lunch_order"` in both `model_id` and `binding_model_id` are unresolved.

I'm using Pycharm 2020.2 and Plugin 4.2 with odoo-stub installed. I'm also sure that the model-related App is included in the dependency.

**Comment by ghost** [comment]
I am not sure, it is working for me:
![Screenshot from 2020-08-01 11-42-38](https://user-images.githubusercontent.com/65052910/89094274-5630c200-d3ec-11ea-9833-dd614d5f4c92.png)

Try **Invalidate Caches / Restart** if it solves your problem.

**Comment by 6uipoeib** [comment]
Interesting. It's been there for days but now gone after I saw this comment.
Anyway, thank you so much for this awesome plugin!
