### ISSUE TITLE
Javascript autocompletion doesn't recognize main javascript function and variables

### ISSUE THREAD

**Issue by LuisMalave2001** [odoo-ide/pycharm-odoo-old#14]
PyCharm by default autocomplete with document or others built-in javascript variables and functions
![image](https://user-images.githubusercontent.com/58850261/89284871-b2dfe700-d64f-11ea-8b66-356cf922844a.png)

But, when I install this plugin, PyCharm doesn't recognize those javascript variables and functions such as parseInt, document, etc:

![image](https://user-images.githubusercontent.com/58850261/89285159-2d106b80-d650-11ea-9a41-239b78160be0.png)

PS: I do really love this plugin, you have done a great job with this.

**Comment by ghost** [comment]
Thank you for your report. The issue was fixed in the new version:
https://github.com/trinhanhngoc/pycharm-odoo/releases/tag/v4.3.1
