### ISSUE TITLE
Python suggestion issue.

### ISSUE THREAD

**Issue by LuisMalave2001** [odoo-ide/pycharm-odoo-old#16]
Greetings

When using self or using env directly it works properly
![image](https://user-images.githubusercontent.com/58850261/89877227-158d3180-dbc0-11ea-8808-81a93ff2f5f4.png)
But, when I try to loop. I doesn't work as it should:
![image](https://user-images.githubusercontent.com/58850261/89877284-2b025b80-dbc0-11ea-8245-14e69a96e2a8.png)

It happens with the relation fields too. I can get suggestion with self.\<one2manyfield> but when I try to loop it, it doens't work.

Thanks

**Comment by ghost** [comment]
You need to attach https://github.com/trinhanhngoc/odoo-stubs to your project to this works, example:

![Screenshot from 2020-08-11 16-18-14](https://user-images.githubusercontent.com/65052910/89880418-6c116480-dbee-11ea-9e05-95636fcae916.png)

**Comment by LuisMalave2001** [comment]
It works correctly, thanks!
