### ISSUE TITLE
Widget field suggestion

### ISSUE THREAD

**Issue by LuisMalave2001** [odoo-ide/pycharm-odoo-old#17]
Greetings,

I would like to make a suggestion if it is possible.

Is there anyway to make the plugin autocomplete the available widget for the fields
![image](https://user-images.githubusercontent.com/58850261/91177625-4dc66100-e6e4-11ea-8423-7aa98255e147.png)

Or even if the plugin can check dynamically for custom widgets. I know it can be hard or even impossible, but it would be great if this feature is implemented

**Comment by trinhanhngoc** [comment]
This feature was implemented in the new version 4.5. I hope you all like it!
