### ISSUE TITLE
[Feature Request] Could you make the widgets to dropdown options in xml

### ISSUE THREAD

**Issue by spoerp** [odoo-ide/pycharm-odoo-old#19]
Odoo has many widgets that can be used in xml fields.

i.e widget_many2many_tags, widget_selection widget_currency etc.

If you could populate the widgets will all the names available when user type "widget=" just like the models get populated, it would be really useful and save tons of time in fixing typos in widget names.

Thanks for your awesome work.

**Comment by trinhanhngoc** [comment]
This feature was implemented in the new version 4.5. I hope you all like it!
