### ISSUE TITLE
[Request] Typescript support

### ISSUE THREAD

**Issue by LuisMalave2001** [odoo-ide/pycharm-odoo-old#20]
I don't know how complex this can be. But I used to use Typescript.
Is possible to integrate odoo javascript autocompletion to typescript?
![image](https://user-images.githubusercontent.com/58850261/93771084-55aeed80-fc1d-11ea-8446-c9a97bd532d2.png)

**Comment by trinhanhngoc** [comment]
I also like TypeScript but I think Odoo does not support TypeScript currently.
