### ISSUE TITLE
Unresolved reference for id and access log fields

### ISSUE THREAD

**Issue by mrm-david** [odoo-ide/pycharm-odoo-old#22]
In odoo14,

Both in views and in python code.

Here's an exemple : 

![](https://user-images.githubusercontent.com/68368989/98527377-3e829880-227b-11eb-943c-62080f1535d2.png)

I don't have odoo-stubs installed (not available for odoo14) but _I do have the odoo source code folder attached_ :

![](https://user-images.githubusercontent.com/68368989/98527901-df715380-227b-11eb-89a5-3b78920b7d76.png)

*   Plugin version is 4.7
*   Pycharm  version 2020.2.3

**Comment by ghost** [comment]
I have not made stubs for odoo 14 yet. While waiting for it, you can use the master branch instead (https://github.com/trinhanhngoc/odoo-stubs/tree/master).

**Comment by mrm-david** [comment]
I still have weird issues with it, would you like me to open another ticket or comment on this one ?
