### ISSUE TITLE
Issue on pycharm 203.xx

### ISSUE THREAD

**Issue by jeroenev** [odoo-ide/pycharm-odoo-old#24]
The plugin has an error message on the latest version of pycharm:
Plugin error: Plugin 'PyCharm Odoo' (version '4.7') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is PY-203.5981.165

**Comment by zloyvetal** [comment]
same issue( need update!

**Comment by iamaswanth** [comment]
![image](https://user-images.githubusercontent.com/49155214/101130213-104d6a00-3629-11eb-9818-1e1ee7c3038b.png)

**Comment by IAY-DGTERA** [comment]
does v 4.8 solve this problem?

**Comment by iamaswanth** [comment]
downlaod the latest package from github then add to pycharm from local disk. 
it seems working for me.

**Comment by jeroenev** [comment]
The latest 4.8 release solves it for me.
Thanks a lot :1st_place_medal:

**Comment by zloyvetal** [comment]
thanks!

**Comment by jeroenev** [comment]
Guess I can close this ticket now
