### ISSUE TITLE
Is there something more to know to setup this?

### ISSUE THREAD

**Issue by HugoDelval** [odoo-ide/pycharm-odoo-old#3]
Hi,

sorry to post an issue here, but I can't find out how to use this module.

I think I did the configuration correctly : 

![image](https://user-images.githubusercontent.com/9109308/78239198-b6b2ff80-74dd-11ea-8341-9972940fd415.png)

I've also installed XPathView

And yet, I still get reference errors in my odoo files, for example if I open `odoo/addons/account_analytic_default/models/account_analytic_default.py` (a file in the official Odoo repo) I see this: 

![image](https://user-images.githubusercontent.com/9109308/78239512-101b2e80-74de-11ea-94d2-b7c2c3c0f3c8.png)

And the completion doesn't seem to work either: 

![image](https://user-images.githubusercontent.com/9109308/78239565-232dfe80-74de-11ea-8a32-ba0b00451643.png)

Am I missing something? 

I'm using the last version of Pycharm and the last version of your plugin in the official Pycharm plugin marketplace. The odoo repository is on the 12.0 branch.

Thanks a lot!

**Comment by trinhanhngoc** [comment]
I am not sure. For example, this is my typical setup:

![Screenshot from 2020-04-02 17-57-28](https://user-images.githubusercontent.com/11208291/78242095-a154ca00-750b-11ea-9ff3-1637a63844af.png)

Try running **Invalidate Caches / Restart...** and restart PyCharm to check if it works for you. Thanks.

**Comment by trinhanhngoc** [comment]
File `account_analytic_default.py` in my test:

![Screenshot from 2020-04-02 18-12-07](https://user-images.githubusercontent.com/11208291/78243273-aca8f500-750d-11ea-9033-528d0499978f.png)

**Comment by HugoDelval** [comment]
Invalidating the caches worked, I don't quite understand why because I restarted Pycharm multiple times.

Thanks a lot for the fast response. It looks like an extremely useful module :pray:
