### ISSUE TITLE
Update plugin for a new pycharm version

### ISSUE THREAD

**Issue by TesaLazarenko** [odoo-ide/pycharm-odoo-old#33]
![image](https://user-images.githubusercontent.com/17133203/114009921-4404fe80-986c-11eb-8c00-5140185d2df2.png)

**Comment by celm1990** [comment]
I get same error

**Comment by srgkm** [comment]
please

**Comment by andreiboyanov** [comment]
yes, please :)

**Comment by trinhanhngoc** [comment]
Hi all. I have just released the new version that supports PyCharm 2021.1. You all can manally download and install from here:
https://github.com/trinhanhngoc/pycharm-odoo/releases/tag/v4.15

**Comment by TesaLazarenko** [comment]
thanks

**Comment by celm1990** [comment]
Thanks, I tested and working fine

**Comment by srgkm** [comment]
Thank you!
