### ISSUE TITLE
Not compatible with PyCharm 211.*

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [odoo-ide/pycharm-odoo-old#34]
Hi, first of all thank you for your contribution.

Plugin 'PyCharm Odoo' (version '4.14') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PC-211.6693.115

Regards.

**Comment by trinhanhngoc** [comment]
Duplicate https://github.com/trinhanhngoc/pycharm-odoo/issues/33
