### ISSUE TITLE
How to use comment to hint type for variables?

### ISSUE THREAD

**Issue by tom10271** [odoo-ide/pycharm-odoo-old#39]
Similar to `@var Product $product` in PHP. If it is not supported now can we have this in the future?

**Comment by mrm-david** [comment]
Do you mean something like this ? https://www.python.org/dev/peps/pep-0484

EDIT: Specifically in the [Type comments](https://www.python.org/dev/peps/pep-0484/#type-comments) section

**Comment by tom10271** [comment]
Yes but not sure how to use it. 

`# type: List[ProductProduct]` hints as ProductProduct's list but the attributes show are all attributes directly marked in that class, all attributes in base class are all missing.

**Comment by mrm-david** [comment]
I think it's because Odoo model inheritance in odoo doesn't use straightforward class inheritance, Odoo does some low level tricks to make it work and probably the type checker (in your IDE or mypy) is confused.

**Comment by tom10271** [comment]
Yeah so that I think from plugin level it might be able to hints the IDE to know more on attributes in classes

**Comment by trinhanhngoc** [comment]
Hi @tom10271 , @mrm-david 

Please follow this issue at https://github.com/trinhanhngoc/pycharm-odoo/issues/12
