### ISSUE TITLE
Unresolve Reference to ignore speical fields

### ISSUE THREAD

**Issue by AdrianTeng** [odoo-ide/pycharm-odoo-old#41]
Thanks for the brilliant plugin!

Odoo has a bunch of special built in fields, namely, `id`, `create_date`, `write_date`, `create_uid`, and `write_uid`, that would appear on every model. As they are not defined in the usual manner, usage of them in XML are currently highlighted as unresolved reference. Would be nice if the plugin could recognise these sepcial fields (I'm guessing adding this at `OdooPyInspectionExtension.java`?)

Example:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/6933071/122506269-8d25bb80-d030-11eb-9386-02f067efd9b9.png">

**Comment by trinhanhngoc** [comment]
Hi @AdrianTeng . You can use https://github.com/trinhanhngoc/odoo-stubs to help the plugin recognize these special fields.

**Comment by AdrianTeng** [comment]
Works like magic! Thanks for the help!

**Comment by AdrianTeng** [comment]
For future reference -- just download the stub repo and import it to your PyCharm project
