### ISSUE TITLE
New field types not recognized

### ISSUE THREAD

**Issue by mrm-david** [odoo-ide/pycharm-odoo-old#42]
Plugin version 4.15 on pycharm 2021.1.

I have a module which uses new fields types : fields.Percent and fields.Permille, defined in another module in the project.

*   Pycharm-odoo doesn't recognise `fields.Percent` and `fields.Permille` in models
*   Pycharm-odoo doesn't autocomplete fields defined as Percent or Permille

Here is an attached sample project with the module that defines the new fields types and a test module that uses them.

[test_pycharm_odoo.zip](https://github.com/trinhanhngoc/pycharm-odoo/files/6675541/test_pycharm_odoo.zip)

**Comment by ghost** [comment]
You imported wrong module to use that custom fields. Correct import is:
```python
from odoo.addons.persign_field.fields import Percent, Permille
```

**Comment by mrm-david** [comment]
Thanks for your help,

So far I only put persign\_fields in the depends section of the manifest. 

I thought that it was all that was needed, so I'm not sure where to put this import ?

**Comment by ghost** [comment]
> Thanks for your help,
> 
> So far I only put persign_fields in the depends section of the manifest. 
> 
> I thought that it was all that was needed, so I'm not sure where to put this import ?

You must put that import in the file in which the fields are used. In the sample project you attached, it is file `test_model.py`  in the module `test_module`.

**Comment by mrm-david** [comment]
Thanks for your reply !

I've tried that in the sample project, but it doesn't work for me : 

![](https://user-images.githubusercontent.com/68368989/122716569-b467cd00-d26a-11eb-8191-12aaa9705eab.png)

Tried also just in case, but it didn't work either :

![](https://user-images.githubusercontent.com/68368989/122716514-a154fd00-d26a-11eb-9654-ed0ee22592d0.png)

**Comment by ghost** [comment]
The field declarations should be updated, example:
```python
pct = fields.Percent()
```
should be
```python
pct = Percent()
```

**Comment by mrm-david** [comment]
Ok this does the trick. Still curious why it worked the original way though. Anyway, thanks a lot for your work. Pycharm-odoo is great.
