### ISSUE TITLE
Error when putting "post_init_hook" inside __manifest__.py

### ISSUE THREAD

**Issue by jcBalmes92** [odoo-ide/pycharm-odoo-old#44]
Using a hook in a module with the following structure:
![image](https://user-images.githubusercontent.com/75234645/124060969-0f808900-d9fc-11eb-92ef-9c2e301ac1dd.png)

The module's \__init__.py file has the following code
![image](https://user-images.githubusercontent.com/75234645/124061108-4ce51680-d9fc-11eb-9946-4e614aafe65a.png)

The module's \__manifest__.py has the following code
![image](https://user-images.githubusercontent.com/75234645/124060826-d2b49200-d9fb-11eb-86de-66ab52782e67.png)

Expected result: pycharm-odoo plugin shouldn't highlight 'post_init_hook' as an error.
Actual result: pycharm-odoo plugin highlights 'post_init_hook' as an error.

**Comment by jcBalmes92** [comment]
Thank you
How can I get this fix in pycharm?

**Comment by ghost** [comment]
Hi @jcBalmes92 ,
I will make a new release in next few days.
