### ISSUE TITLE
Odoo docker remote interpreter

### ISSUE THREAD

**Issue by floflock** [odoo-ide/pycharm-odoo-old#49]
I develop with the official docker image and the locally running docker container is configured as remote interpreter in PyCharm. The plugin does not recognise the odoo dist-packages properly.

![image](https://user-images.githubusercontent.com/3831745/126388323-d2b8f385-a307-4b90-a13e-02991f47fd32.png)

The sources are shown under "External Libraries":
![image](https://user-images.githubusercontent.com/3831745/126388390-d0348963-a219-4f76-92bc-40343629ba95.png)

Is it on the roadmap that the plugin can deal with docker containers?

**Comment by trinhanhngoc** [comment]
Hi @floflock ,
 
Please follow this issue at https://github.com/trinhanhngoc/pycharm-odoo/issues/13. Thank you for reporting.
