### ISSUE TITLE
Unresolved reference 'write_date'?

### ISSUE THREAD

**Issue by minimedj** [odoo-ide/pycharm-odoo-old#9]
Why 'write_date' is unresolved?

Here is a screenshot: https://monosnap.com/file/NrOv4zjduPSqwyWm8Fv9TjMJKpRvbj

**Comment by ghost** [comment]
What Pycharm Odoo plugin version are you using ? Did you attach https://github.com/trinhanhngoc/odoo-stubs to your project ?

**Comment by minimedj** [comment]
With odoo-stubs it is better. Thanks!

**Comment by ghost** [comment]
Please use the odoo stubs in the branch correspond to the odoo version, see https://github.com/trinhanhngoc/odoo-stubs/issues/1#issuecomment-632098464
